name: 'GoFile Uploader'
description: 'A GitHub Action to upload files to GoFile.io'
author: 'toiletpuppy & 7jari'
branding:
  icon: upload
  color: yellow
inputs:
  files:
    description: 'Space-separated list of file paths to upload'
    required: true
  server:
    description: 'Server to upload to'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run upload script
      run: gofile.sh ${{ inputs.files }}
      shell: bash
      env:
        SERVER: ${{ inputs.server }}
